version: '3.9'
services:
  web:
    build: .
    command: flask run --host=0.0.0.0 --port=5060
    volumes:
      - .:/app
    ports:
      - "5060:5060"
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A app.celery worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
